import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import useFetch from '../../hooks/useFetch'
import Link from 'next/link'
import { useRouter } from "next/router";
import {useQuery, gql} from '@apollo/client'


const REVIEW = gql`
    query GetReview($id: ID!){
        review(id: $id){
            title,
            body,
            rating,
            id
        }
    }
`

export default function SingleReview() {
  const router = useRouter();
  const param = router.query.id;
  //const {loading, error, data } = useFetch(`http://localhost:1337/reviews/${param}`);
  const {loading, error, data } = useQuery(REVIEW,{
      variables: {id: parseInt(param)}
  });

  if(loading) return <p>Loading......</p>
  if(error) return <p>Error :(</p>
    
  return (
    <div className={styles.container}>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <h1>Single Reviews</h1>
        <div>
            <div style={{marginBottom: '10px', borderBottom: '1px solid #ccc', paddingBottom: '15px'}}>
                <p style={{marginBottom: '0'}}>{data.review.rating}</p>
                <h2 style={{marginTop: '5px'}}>{data.review.title}</h2>
                <small>categories</small>
                <p>{data.review.body}</p>
                <Link href={`/reviews`}><span style={{color:'blue', cursor: 'pointer'}}>Back</span></Link>
            </div>
        </div>
        
    </div>
  )
}
